name: Deploy Discovery Service

on:
  push:
    branches:
      - main
    paths:
      - "discovery-service/**"

jobs:
  build:
    name: Deploy Disocvery Service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew :discovery-service:build

